### ISSUE TITLE
Give the SDK packages a little love

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-SDK#53] opened 2019-02-23 12:34 UTC
We should not put code into index.js. Node uses the index.js file to look up files in a folder.

The "index.js" file has the purpose to expose & prepare an interface for a folder/unit.

Furthermore, all the code lives mostly in one file (in the index.js). Would be great to split up little units.

Both enhancements will help other (SDK) developers to follow & understand the code.

This has lower priority for now, but this is a perfect post cleanup task 👍

**Comment by kevinansfield** [comment] 2019-07-03 10:45
Closing as duplicate of https://github.com/TryGhost/Ghost-SDK/issues/74

**Closed by kevinansfield** 2019-07-03 10:45 UTC
Labels: cleanup
