### ISSUE TITLE
AdminAPI: getting UPDATE_COLLISION

### ISSUE THREAD

**Issue by vmarkovtsev** [TryGhost/Ghost-SDK#103] opened 2019-05-09 09:57 UTC
### Issue Summary

I am unable to update a post using Admin API. I get `UPDATE_COLLISION` error.

### To Reproduce

I run
```js
await api.posts.edit({"id": "5c8051da2a25b600c01ff9ee", "mobiledoc": JSON.stringify(md), "updated_at": "2019-05-09T11:39:37.000Z"})
```

and get

```
{ UpdateCollisionError: Saving failed! Someone else is editing this post.
    at makeRequest.catch (/tmp/node_modules/@tryghost/admin-api/lib/index.js:292:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'UpdateCollisionError',
  context: 'Saving failed! Someone else is editing this post.',
  type: 'UpdateCollisionError',
  details:
   { clientUpdatedAt: '2019-05-09T11:39:37.000Z',
     serverUpdatedAt: '2019-05-08T15:40:57.000Z' },
  property: null,
  help: null,
  code: 'UPDATE_COLLISION',
  id: '36069d20-723f-11e9-9b05-d55f47be1c26' }
```

I guarantee that nobody else is editing that post. I don't have it open in a web browser, and nobody else knows that the post I am editing even exists.

### Technical details:

* Ghost Version: 2.22
* Node Version: v10.15.3
* Browser/OS: N/A
* Database: N/A

### P.S.

JS API docs suck. I mean, really suck. Typos ("api.pages.edit" instead of "api.posts.edit"), "updated_at" is not included, there is only one example (to publish). It's a miracle that I ever found how to use it all.

![image](https://user-images.githubusercontent.com/2793551/57444870-6ab9f500-7251-11e9-95c3-a1348d0def4d.png)

**Comment by kevinansfield** [comment] 2019-05-09 10:01
> JS API docs suck. I mean, really suck.

The docs are still very much WIP and the Admin API has not been officially announced/released yet. All of the API docs pages have links to the github repo where you can submit edits or fixes, doing that is much more helpful than getting angry that your free code isn't well documented 😉 

I'm closing this issue as it's not a bug but a misuse of the API, for help/support using the API please use [our forum](https://forum.ghost.org)

**Closed** 2019-05-09 10:02 UTC

**Comment by vmarkovtsev** [comment] 2019-05-09 10:31
@kevinansfield That's a very good excuse to not (at least) fix misleading API error messages.

**Comment by markstos** [comment] 2022-06-18 21:21
For anyone else who ends up here because they tried to use the Admin API to update the `updated_at` field:

It appears this will never work right now, because Ghost uses the `updated_at` field for collision detection. It will always throws this error when the submitted `updated_at` field differs from the servers `updated_at` field. The code that does that is here:

https://github.com/TryGhost/framework/commit/b52430024e1ce72ebbf79e7d49faa3db2335731d#diff-2a6bad6183d9e7cb3c1ad8f864838f296a0dff38553a49755a7c5f12e8d1adbeR56

It looks like server manages updating the `updated_at` time itself, so there's no need to submit updated values through the API.

**Comment by vikram-ray** [comment] 2023-02-18 12:16
> For anyone else who ends up here because they tried to use the Admin API to update the `updated_at` field:
> 
> It appears this will never work right now, because Ghost uses the `updated_at` field for collision detection. It will always throws this error when the submitted `updated_at` field differs from the servers `updated_at` field. The code that does that is here:
> 
> [TryGhost/framework@b524300#diff-2a6bad6183d9e7cb3c1ad8f864838f296a0dff38553a49755a7c5f12e8d1adbeR56](https://github.com/TryGhost/framework/commit/b52430024e1ce72ebbf79e7d49faa3db2335731d#diff-2a6bad6183d9e7cb3c1ad8f864838f296a0dff38553a49755a7c5f12e8d1adbeR56)
> 
> It looks like server manages updating the `updated_at` time itself, so there's no need to submit updated values through the API.

I tried editing a post but after looking at the response, look like updated_at is mandatory.

`"params":{"missingProperty":"updated_at"},"message":"should have required property 'updated_at'"}],`

**Comment by WebShapedBiz** [comment] 2023-03-05 19:32
I'm a paying Ghost(Pro) customer @kevinansfield, and have to use the same SDK documentation that @vmarkovtsev is talking about. So now what?

**Comment by markstos** [comment] 2023-05-19 13:53
It appears my above comment was not accurate. This issue has also been discussed on the official Ghost Forum:

https://forum.ghost.org/t/post-update-with-api-and-update-date/20234

I'm a moderator there and have asked the Ghost team to make the document more complete and accurate. It's not clear that the official docs are in a public repo that we can submit PRs against.
